### ISSUE TITLE
Re-rendering plot when the any state of the component changes

### ISSUE THREAD

**Issue by vaasu070** [reactchartjs/react-chartjs-2#648]
This behaviour was not observed with older version of chartjs. i.e version less than 3. 
When ever the state of the component changes , entire plot re renders again as if it is rendering for the first time. sample code to this behaviour is [here](https://codesandbox.io/s/quirky-noether-8y9e0?file=/src/App.js)

**Comment by YakovlevCoded** [comment]
Yeah, thanks. i will work with it issue.

**Comment by YakovlevCoded** [comment]
@vaasu070 I have released a[ test package](https://www.npmjs.com/package/test-react-chartjs-2) that solves this problem. Could I ask to try it out. And if everything is OK, I will release a minor version with an edit.

**Comment by vaasu070** [comment]
@YakovlevCoded  yeah now It is working as expected. Thanks for looking into it.

**Comment by vaasu070** [comment]
@YakovlevCoded , I observed one more issue with test-react-chartjs-2 package, whenever data is updated, the chart  fails to show the new data. This can be observed [here ](https://codesandbox.io/s/react-chartjs-2-bar-example-forked-rkp0d?file=/src/index.js).

**Comment by YakovlevCoded** [comment]
@vaasu070 Thank you! I will work on it.

**Comment by vaasu070** [comment]
A new version 3.0.3 is rolled out, But the above bug still exists in it [here](https://codesandbox.io/s/test-react-chartjs-2-bar-rkp0d?file=/src/index.js).  If its not too early to ask, when it will be fixed and released? Its quite critical for out project Thanks.

**Comment by YakovlevCoded** [comment]
@vaasu070 If it's critical I'll try to finish it in the next couple of days

**Comment by vaasu070** [comment]
> @vaasu070 If it's critical I'll try to finish it in the next couple of days. I'll let you know as soon as I'm done with this.

Would really appreciate this!

**Comment by revroad-dev** [comment]
The re-rendering still seems to be a an issue on current version 3.0.3. This was not an issue in chart.js v2.9.4

When the state changes the donut is redrawn/reanimated. Desired behavior is to rotate the doughnut without redrawing the the graph.

```
export default function KChart() {
  const [rotation, setRotation] = useState(0);
  const onClick = () => {
    setRotation(rotation + 20);
  };
  const data = {
    labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    datasets: [
      {
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        borderColor: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        borderWidth: 1,
      },
    ],
  };
  return <Doughnut type="doughnut" data={data} options={{ rotation, onClick }} />;
}
```

**Comment by revroad-dev** [comment]
The above happens on all chart types whether or not the state is passed to the component or not. (in other words, taking rotation out of the options objects still results in the same re-rendering behavior)

**Comment by ntamas** [comment]
I'm using the following patch as a band-aid until the issue is fixed properly. This probably does not cover all use-cases (it definitely doesn't handle datasets being removed from the chart), but it works for me with a simple bar chart that is refreshed every second:

```diff
diff --git a/node_modules/react-chartjs-2/dist/index.modern.js b/node_modules/react-chartjs-2/dist/index.modern.js
index f39264d..f8636d6 100644
--- a/node_modules/react-chartjs-2/dist/index.modern.js
+++ b/node_modules/react-chartjs-2/dist/index.modern.js
@@ -117,11 +117,14 @@ var ChartComponent = forwardRef(function (props, ref) {
     var _chart$config$data$da = chart.config.data.datasets,
         currentDataSets = _chart$config$data$da === void 0 ? [] : _chart$config$data$da;
     assign(chart.config.data, newChartData);
-    chart.config.data.datasets = newDataSets.map(function (newDataSet) {
+    newDataSets.forEach(function (newDataSet) {
       var currentDataSet = find(currentDataSets, function (d) {
         return d.label === newDataSet.label && d.type === newDataSet.type;
       });
-      if (!currentDataSet || !newDataSet.data) return newDataSet;
+      if (!currentDataSet) {
+        currentDataSet = {};
+        currentDataSets.push(currentDataSet);
+      }

       if (!currentDataSet.data) {
         currentDataSet.data = [];
@@ -130,7 +133,7 @@ var ChartComponent = forwardRef(function (props, ref) {
       }

       assign(currentDataSet.data, newDataSet.data);
-      return _extends({}, currentDataSet, newDataSet, {
+      assign(currentDataSet, newDataSet, {
         data: currentDataSet.data
       });
     });
```

**Comment by revroad-dev** [comment]
Hi, @YakovlevCoded thanks for all your hard work so far. Is this fix getting close to being released?

**Comment by maidinhkhoa92** [comment]
I'm having same issue. Can I ask about release time ?

**Comment by vaasu070** [comment]
Hi @YakovlevCoded any update on this?

**Comment by marcusround** [comment]
I have also run into this issue ( I posted about it here: https://github.com/reactchartjs/react-chartjs-2/issues/678 )
The `test-react-chartjs-2` branch DID fix the issue.
However, there seems to be a separate issue with that branch, in that all my bars stopped drawing. It is because I was using `data` as a function: `data: (canvas) => {  return { /*...*/ } }` so that I could use canvas patterns as a `backgroundColor`. If I change `data` to a normal object: `data: { /*...*/ }`, the bars draw fine, and the animation works.

**Comment by vaasu070** [comment]
> I have also run into this issue ( I posted about it here: #678 )
> The `test-react-chartjs-2` branch DID fix the issue.
> However, there seems to be a separate issue with that branch, in that all my bars stopped drawing. It is because I was using `data` as a function: `data: (canvas) => { return { /*...*/ } }` so that I could use canvas patterns as a `backgroundColor`. If I change `data` to a normal object: `data: { /*...*/ }`, the bars draw fine, and the animation works.

To add to your observation on `test-react-chartjs-2` , whenever data is updated, the chart fails to show the new data. It is always showing the initial data. This can be observed [here](https://codesandbox.io/s/react-chartjs-2-bar-example-forked-rkp0d?file=/src/index.js)

**Comment by marcusround** [comment]
> To add to your observation on `test-react-chartjs-2` , whenever data is updated, the chart fails to show the new data. It always shows initial data. This can be observed [here](https://codesandbox.io/s/react-chartjs-2-bar-example-forked-rkp0d?file=/src/index.js)

I am not sure what you mean exactly but I think its an issue with your code - see my working fork [here](https://codesandbox.io/s/xgie8)

For my patterns issue, I have illustrated it [here](https://codesandbox.io/s/21s3u)

**Comment by vaasu070** [comment]
> > To add to your observation on `test-react-chartjs-2` , whenever data is updated, the chart fails to show the new data. It always shows initial data. This can be observed [here](https://codesandbox.io/s/react-chartjs-2-bar-example-forked-rkp0d?file=/src/index.js)
> 
> I am not sure what you mean exactly but I think its an issue with your code - see my working fork [here](https://codesandbox.io/s/xgie8)
> 
> For my patterns issue, I have illustrated it [here](https://codesandbox.io/s/21s3u)

I was saying with `test-react-chartjs-2` package in the code sample [here](https://codesandbox.io/s/react-chartjs-2-bar-example-forked-rkp0d?file=/src/index.j)s, initial data is `{}` and later data is changed to 
```
{
  labels: [1, 2, 3, 4],
  datasets: [
    {
      data: [1, 2, 3, 4]
    }
  ]
}
```.
But this is not reflected on the plot. with  `react-chartjs-2` it works perfectly fine.

**Comment by joey-carlisle4** [comment]
I have a similar issue and am awaiting a conclusion.

**Comment by marcusround** [comment]
> 
> 
> I have a similar issue and am awaiting a conclusion.

For what its worth I was able to fix the issue (without introducing the patterns bug) by using the fix suggested by @ntamas in this thread.

**Comment by Luc9802** [comment]
Encountered the same problem, it seems quite critical.

**Comment by joey-carlisle4** [comment]
> > I have a similar issue and am awaiting a conclusion.
> 
> For what its worth I was able to fix the issue (without introducing the patterns bug) by using the fix suggested by @ntamas in this thread.

I thought the fix was going to involve a custom build.  Once I realized its just patching local node_modules, I realized its not as scary as it looks.  Good fix for now!

**Comment by davidkipstar** [comment]
Hello,
I tried to apply the patch and also tried out test-react-chartjs-2 branch but with Bubble Chart, apparently it is not working with the patch and on the test branch I get no render at all. Did someone try this patch with Bubble Chart and succeded?

**Comment by maidinhkhoa92** [comment]
@vaasu070 I found how to render with new value.
you can combine test-react-chartjs-2 and useState
When fetching new data, loading is true. Loading state is false when you have new data

```
{loading ? (
                <Spinner />
              ) : (
                    <LineChart
                      params={params}
                      chartResponse={chartLineResponse}
                      isBoundary={isBoundary}
                      isZoom={isZoom}
                      averageValue={averageValue.value}
                      measurement={measurement.value}
                    />
              )}
```

**Comment by csmartinsfct** [comment]
> @vaasu070 I have released a[ test package](https://www.npmjs.com/package/test-react-chartjs-2) that solves this problem. Could I ask to try it out. And if everything is OK, I will release a minor version with an edit.

the package worked fine for me, thanks!

**Comment by mssrmaps** [comment]
I am having a similar issue, where a re-render due to state change on one chart component is causing a re-render on all charts (in their own components) under the same parent component to the parent of the one that had the state change.

This is occurring with hover, new data, etc. This did not occur on chart.js versions 2.9.4 and earlier. The resulting animations from the re-render are undesirable and I worry of related performance hits.  

Is this a related issue to what is being described here?

**Comment by csmartinsfct** [comment]
> I am having a similar issue, where a re-render due to state change on one chart component is causing a re-render on all charts (in their own components) under the same parent component to the parent of the one that had the state change.
> 
> This is occurring with hover, new data, etc. This did not occur on chart.js versions 2.9.4 and earlier. The resulting animations from the re-render are undesirable and I worry of related performance hits.
> 
> Is this a related issue to what is being described here?

Yes, try [this](https://www.npmjs.com/package/test-react-chartjs-2) package if you can and let people know if it works for you :)

**Comment by jordanlapointe** [comment]
@csmartinsfct This works beautifully for data changes!

I did notice one issue where pointRadius callbacks are now only called on the initial render. I will get a simpler use case together later this week, but this is the gist:

```js
const activeAccountChartData = {
  labels: someLabelDataArray,
  datasets: [
    {
      data: accountDataByMonth,
      pointRadius: (context) => {
        const index = context.dataIndex;
        const label = context.chart.config.data.labels[index];
        const isSelected = label === activeMonth;
        return isSelected ? 8 : 4;
      },
    },
  ],
};

return (
  <Line
    data={activeAccountChartData}
    options={chartOptionsDefault}
  />
);
```

**Comment by mssrmaps** [comment]
@csmartinsfct thanks for the suggestion! It's likely I am doing something unanticipated by this test package. Upon switching over to it I receive the error shown in the image below. This error is not present when importing the released version. 

![image](https://user-images.githubusercontent.com/64438288/123663299-1c7a5e00-d7eb-11eb-9cde-dd6b42ab87e9.png)

**Comment by dominicboston** [comment]
So pleased I found this test package - this solved the problem for me. Subscribing to find out when this will be merged.

> Yes, try [this](https://www.npmjs.com/package/test-react-chartjs-2) package if you can and let people know if it works for you :)

**Comment by Luc9802** [comment]
> > I am having a similar issue, where a re-render due to state change on one chart component is causing a re-render on all charts (in their own components) under the same parent component to the parent of the one that had the state change.
> > This is occurring with hover, new data, etc. This did not occur on chart.js versions 2.9.4 and earlier. The resulting animations from the re-render are undesirable and I worry of related performance hits.
> > Is this a related issue to what is being described here?
> 
> Yes, try [this](https://www.npmjs.com/package/test-react-chartjs-2) package if you can and let people know if it works for you :)

There is a problem with background colors when they are dynamic.
I made an example of the behavior, you can find it here: https://codesandbox.io/s/romantic-waterfall-cdl8f?file=/src/App.js

Basically the chart is initialized with 3 random data values and colors,
Then you can add dynamically sections, this generate a new random data value and color.
Sections generated after the 3rd, re-uses alternatively the colors of the first 3 data instead of their own.

In the example I list the values and colors apart to see the real data state and the behavior of the chart.

![image](https://user-images.githubusercontent.com/71693205/123673286-94bf3e80-d840-11eb-8bbf-ebd26dea21d0.png)

**Comment by daviavmello** [comment]
Very interesting solution by @ntamas. Very curious to know when this will be merged.

**Comment by nohaapav** [comment]
Stacked bar chart with x axis set to type "time" is broken as well with test-package. Not rendering any data. With normal package works ok.

**Comment by dominicboston** [comment]
Just came across this new bug that doesn't happen on the original package just on the test package. Not sure if this is my fault or not just posting incase anyone knows if this is a fixable issue. Just changed a state that filters the datasets. 

![Screenshot 2021-07-07 at 11 07 31](https://user-images.githubusercontent.com/42346977/124741408-914c4700-df13-11eb-999c-9ed7078fb0fb.png)

**Comment by PCPbiscuit** [comment]
> So pleased I found this test package - this solved the problem for me. Subscribing to find out when this will be merged.
> 
> > Yes, try [this](https://www.npmjs.com/package/test-react-chartjs-2) package if you can and let people know if it works for you :)

This test package saved me with my custom tooltip since every hover would rerender the whole chart however now it still updates nonstop while I'm hovering resulting in  "Warning: Maximum update depth exceeded.". Not really sure how to deal with this one

**Comment by hardy12994** [comment]
This resolves my issue!

```
const LineChart = () => <Line data={data} options={options} />
const areEqual = (prevProps, nextProps) => true;

export default React.memo(LineChart, areEqual);
```
[React Memo Document
](https://reactjs.org/docs/react-api.html#reactmemo)

**Comment by dominicboston** [comment]
> This resolves my issue!
> 
> ```
> const LineChart = () => <Line data={data} options={options} />
> const areEqual = (prevProps, nextProps) => true;
> 
> export default React.memo(LineChart, areEqual);
> ```
> 
> [React Memo Document](https://reactjs.org/docs/react-api.html#reactmemo)

This temp solution works for me too, be good to understand why this is happening on the test package and not the original.

Thanks

**Comment by daviavmello** [comment]
I was able to fix this going off of @hardy12994's solution:

`
const handleClick = useCallback(() => {
}, []), 
const memoizedChart = useMemo(DonutChart, [handleClick, data]);
`

**Comment by YassienW** [comment]
Experiencing the same issue, chart re-renders from scratch on both data changes and parent component re-renders. Seems to be fixed on `test-react-chartjs-2`
The memo fix seems to only fix part of the problem (unnecessary rerenders but not data changes)

I am wondering why a relatively critical issue like this hasn't been merged yet.

**Comment by ostrebler** [comment]
Same problem here. I'm going back to version 2 for the time being.

**Comment by ae0n** [comment]
`test-react-chartjs-2` is fixing this problem. Please include those changes in a new minor version

**Comment by enjineerMan** [comment]
I'm using chartjs-plugin-zoom for zooming and panning. On zoom or pan events, and function called `getVisibleValues` is triggered that calls a setState function passed through props. However, calling this function resets the chart back to its default position, which makes panning or zooming impossible. I've tried both test-react-chartjs-2 and @ntamas ' fix, but the issue persists. 

```
const SingleChart = ({ chosenDevice, variable, setVisible }) => {
  const [chartData, setChartData] = useState({
    labels: [],
    datasets: [
      {
        label: variable,
        data: [],
        fill: false,
        backgroundColor: "rgb(0,0,0)",
        borderColor: "rgba(0,0,0, 0.8)",
        color: "rgb(0,0,0)",
        pointRadius: 4,
        yAxisID: "y",
      },
    ],
  });
  const [apiData, setApiData] = useState({});
  const processEnv = process.env;

  function getVisibleValues({ chart }) {
    setVisible(chart.scales.x.ticks); //calling callback setState function
  }
  const chartStyle = {
    options: {
      animation: false,
      maintainAspectRatio: true,
      responsive: true,
      plugins: {
        zoom: {
          zoom: {
            wheel: {
              enabled: true,
              modifierKey: "shift",
            },
            pinch: {
              enabled: true,
            },
            enabled: true,
            drag: true,
            mode: "x",
            onZoomComplete: getVisibleValues,
          },
          pan: {
            enabled: true,
            mode: "x",
            speed: 2,
            onPanComplete: getVisibleValues,
          },
          mode: "xy",
        },
        legend: {
          display: false,
        },
      },

      scales: {
        y: {
          type: "linear",
          display: "true",
          position: "left",
          grid: {
            drawBorder: true,
            color: "#000000",
          },
          ticks: {
            beginAtZero: true,
            color: "#000000",
          },
        },

        x: {
          max: 9,
          grid: {
            drawBorder: true,
            color: "#00000",
          },
          ticks: {
            beginAtZero: false,
            color: "#000000",
          },
        },
      },
    },
  };

// code here removed for decluttering, gets chartData from an API

  return (
    <div>
      <Line
        data={chartData}
        options={variable != "GEN_ON" ? chartStyle.options : genStyle.options}
        width={20}
        height={10}
      />
    </div>
  );
};
```

**Comment by M4sterShake** [comment]
Hey, is there any update on this issue? Its quite a major problem for us and I'm wondering whether we'll have to switch to using chart.js directly before we go live. Thanks

**Comment by PCPbiscuit** [comment]
@M4sterShake Same here.

**Comment by mssrmaps** [comment]
@PCPbiscuit @M4sterShake 
me too

**Comment by M4sterShake** [comment]
@PCPBiscuit @mssrmaps I've just tried upgrading to 3.0.5 and it fixed the issue for me. If you guys aren't on this version give it a go. Hope it works!

**Comment by M4sterShake** [comment]
Just to help clarify things for anyone reading this thread, it looks like this issue is fixed in 3.0.5. @YakovlevCoded it can probably be closed unless anyone has an issue after upgrading to 3.0.5.

**Comment by Elius94** [comment]
For me the bug is still alive :( same as previous post says

**Comment by dangreen** [comment]
@larinius Hi. Please provide issue reproduction. You can fok codesandbox from examples.

**Comment by awhite9** [comment]
@larinius - this might be a little late - but I just spent a week wracking my brain over performance issues rendering pages with multiple charts with very large datasets constantly re-rendering every time the parent stat changed - slowing down my entire page.... React memo solved my issue - basically made my child components with the chartjs components no re render every time the parent does, only when its down state or props change

**Comment by wayneschuller** [comment]
> @larinius - React memo solved my issue - basically made my child components with the chartjs components no re render every time the parent does, only when its down state or props change

Can you post sample code with useMemo and react-chartjs-2 chart improvements?

**Comment by quyendaoqt707** [comment]
@wayneschuller Thanks to @awhite9's suggestion, I fixed the re-rendering issue in react-chartjs-2 v5.3.0 and Chart.js v4.4.9 using useMemo. Here's a code sample; hope it helps others.

```jsx
// React component
const data = prepareYourDataHere(props.rawData)

// use useMemo to 'cache'  the chart data
const dataMemo = useMemo(() => {
        return data
    }, [props.rawData]) 

    return (
        <div
            style={{
                width: '100%',
            }}
        >
            <Bar
                data={dataMemo}
                options={options}
                plugins={[]}
            />
        </div>
    )
```
